# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Ladislav's Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lslezak.github.io" # the base hostname & protocol for your site
github_username:  lslezak

# see http://kramdown.gettalong.org/syntax.html for the format specification
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  hard_wrap: false

permalink: /:year/:month/:day/:title/

# generate sitemap.xml and feed.xml automatically by plugins
gems:
  - jekyll-sitemap
  - jekyll-feed

# exclude some files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
