# If you change this file, please restart the local server process.

# site settings
title: The Ladislav's Blog
email: lad.slezak@gmail.com
description: >
  This is my personal blog about Linux, programming and related stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.ladslezak.cz" # the base hostname & protocol for your site
github_username:  lslezak

# see http://kramdown.gettalong.org/syntax.html for the format specification
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # no hard line endings, allow reformatting paragraphs
  hard_wrap: false

permalink: /:year/:month/:day/:title/

# generate sitemap.xml and feed.xml automatically by plugins, enable GFM emoji
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# exclude some files
exclude:
  - firebase.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .tags
  - .tags1
